name: Auto Deploy
on:
    push:
        branches: dev

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: Deploy
        steps:
            - name: Remote SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                    cd ~/blog
                    git pull origin dev
                    npm install
                    npm build